#!/usr/bin/env bash
#process and pid file

touch "/var/run/myscript.pid"
while true
do	
	echo "To infinity and beyond"
	trap "echo Y U no love me?!" SIGINT
	trap "echo I hate the kill command; rm /var/run/myscript.pid; exit 0" SIGQUIT SIGTERM
done
