#!/usr/bin/env bash
#bash clock
# shellcheck disable=SC2004

hour=0
min=1
while [ $hour -lt 12 ]; do
	echo "Hour: $hour"
	min=1
	while [ $min -lt 60 ]; do
		echo $min
		min=$(($min+1))
	done
	hour=$(($hour+1))
done
echo "Hour: 12"
